export const initialNotifications = [
  {
    id: 'n1',
    title: 'New assignment posted',
    text: 'Professor Lefevre shared the Week 3 assignment.',
    time: '2m ago',
  },
  {
    id: 'n2',
    title: 'File uploaded',
    text: 'Course syllabus has been updated in Resources.',
    time: '45m ago',
  },
  {
    id: 'n3',
    title: 'Meeting scheduled',
    text: 'Weekly review room is open for L1 Informatics.',
    time: '1h ago',
  },
]

export const initialClasses = [
  {
    id: 'l1-inf',
    name: 'L1 Informatics',
    description: 'Fundamentals of programming, architecture, and networks.',
    channels: [
      { id: 'general', name: 'General', type: 'chat' },
      { id: 'announcements', name: 'Announcements', type: 'announcements' },
      { id: 'assignments', name: 'Assignments', type: 'chat' },
      { id: 'resources', name: 'Resources', type: 'files' },
      { id: 'exams', name: 'Exams', type: 'chat' },
      { id: 'voice', name: 'Voice Channel', type: 'voice' },
      { id: 'meeting', name: 'Meeting Room', type: 'meeting' },
    ],
    members: [
      { id: 'u1', name: 'Alice Lefevre', role: 'Professor' },
      { id: 'u2', name: 'Thomas Nguyen', role: 'Student' },
      { id: 'u3', name: 'Mariam Diallo', role: 'Student' },
      { id: 'u4', name: 'Jules Martin', role: 'Student' },
    ],
    messages: [
      {
        id: 'm1',
        channel: 'general',
        author: 'Alice Lefevre',
        role: 'Professor',
        text: 'Bienvenue dans L1 Informatics! Start by checking the Resources tab for the course syllabus and the first lecture notes.',
        time: '09:10 AM',
        reactions: { like: 2 },
        mentions: ['@Thomas Nguyen'],
      },
      {
        id: 'm2',
        channel: 'general',
        author: 'Thomas Nguyen',
        role: 'Student',
        text: 'Merci! Can someone share the homework deadline for this week?',
        time: '09:22 AM',
        reactions: { like: 1 },
        mentions: [],
      },
      {
        id: 'm3',
        channel: 'assignments',
        author: 'Alice Lefevre',
        role: 'Professor',
        text: 'Assignment 1 is now available. You can submit via the Files tab or email me if you have any issue.',
        time: '09:45 AM',
        reactions: { like: 3 },
        mentions: [],
      },
      {
        id: 'm4',
        channel: 'exams',
        author: 'Mariam Diallo',
        role: 'Student',
        text: 'Does anyone know the format for the midterm exam?',
        time: '10:05 AM',
        reactions: { like: 0 },
        mentions: ['@Jules Martin'],
      },
    ],
    announcements: [
      {
        id: 'a1',
        title: 'Project kickoff',
        author: 'Alice Lefevre',
        date: 'Jun 10, 2026',
        body: 'The term project teams will be announced next Monday. Start reviewing the requirements in Resources and prepare your first proposal.',
      },
      {
        id: 'a2',
        title: 'Course syllabus updated',
        author: 'Alice Lefevre',
        date: 'Jun 6, 2026',
        body: 'I uploaded the final syllabus and assessment plan. Please read the grading rubric before the next lecture.',
      },
    ],
    files: [
      {
        id: 'f1',
        name: 'Course Syllabus.pdf',
        type: 'PDF',
        size: '240 KB',
        uploadedBy: 'Alice Lefevre',
        updatedAt: 'Jun 6, 2026',
      },
      {
        id: 'f2',
        name: 'Week 1 Lecture Notes.pdf',
        type: 'PDF',
        size: '1.2 MB',
        uploadedBy: 'Alice Lefevre',
        updatedAt: 'Jun 4, 2026',
      },
      {
        id: 'f3',
        name: 'L1_INF_Class_List.xlsx',
        type: 'XLSX',
        size: '85 KB',
        uploadedBy: 'Admin',
        updatedAt: 'Jun 1, 2026',
      },
    ],
    meeting: {
      title: 'Weekly Review Room',
      description: 'Weekly live meeting for Q&A, announcements, and collaboration.',
      status: 'scheduled',
      participants: [
        { id: 'u1', name: 'Alice Lefevre', role: 'Professor' },
        { id: 'u2', name: 'Thomas Nguyen', role: 'Student' },
        { id: 'u3', name: 'Mariam Diallo', role: 'Student' },
      ],
      startedAt: 'Jun 11, 2026 • 14:00',
      room: 'Room 02',
    },
  },
  {
    id: 'l2-net',
    name: 'L2 Networks',
    description: 'Switching, routing, and network security.',
    channels: [
      { id: 'general', name: 'General', type: 'chat' },
      { id: 'announcements', name: 'Announcements', type: 'announcements' },
      { id: 'resources', name: 'Resources', type: 'files' },
      { id: 'exams', name: 'Exams', type: 'chat' },
      { id: 'voice', name: 'Voice Channel', type: 'voice' },
      { id: 'meeting', name: 'Meeting Room', type: 'meeting' },
    ],
    members: [
      { id: 'u5', name: 'Thomas Laurent', role: 'Professor' },
      { id: 'u6', name: 'Nadia Kone', role: 'Student' },
      { id: 'u7', name: 'Luc Besson', role: 'Student' },
    ],
    messages: [
      {
        id: 'm5',
        channel: 'general',
        author: 'Thomas Laurent',
        role: 'Professor',
        text: 'Welcome to L2 Networks. Start by reviewing the lab guides in Resources before the first practical session.',
        time: '08:50 AM',
        reactions: { like: 4 },
        mentions: [],
      },
      {
        id: 'm6',
        channel: 'exams',
        author: 'Nadia Kone',
        role: 'Student',
        text: 'Is the network design assignment due next Friday or the following week?',
        time: '09:15 AM',
        reactions: { like: 1 },
        mentions: [],
      },
    ],
    announcements: [
      {
        id: 'a3',
        title: 'Lab environment ready',
        author: 'Thomas Laurent',
        date: 'Jun 8, 2026',
        body: 'The lab environment is now available. Connect to the virtual network at the URL shared on the course page.',
      },
    ],
    files: [
      {
        id: 'f4',
        name: 'Network Lab Guide.pdf',
        type: 'PDF',
        size: '1.8 MB',
        uploadedBy: 'Thomas Laurent',
        updatedAt: 'Jun 8, 2026',
      },
    ],
    meeting: {
      title: 'Topology Review Session',
      description: 'Pair up to compare network designs and review routing strategies.',
      status: 'scheduled',
      participants: [
        { id: 'u5', name: 'Thomas Laurent', role: 'Professor' },
        { id: 'u6', name: 'Nadia Kone', role: 'Student' },
        { id: 'u7', name: 'Luc Besson', role: 'Student' },
      ],
      startedAt: 'Jun 12, 2026 • 16:30',
      room: 'Room 05',
    },
  },
]
